name: jd daily scripts

on:
  push:
    branches:
      - dev
  schedule:
    - cron: '0 10 * * 4'

env:
  NODE_VERSION: '10.x'                # set this to the node version to use

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install, build, and test
      run: |
        cd ./jd_scripts
        npm install || npm install --registry=https://registry.npm.taobao.org
        node ./jd_speed.js