name: Python Package using Conda

on: [push]

jobs:
  epic_game:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Set up Python 3.7'
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: python -m pip install --upgrade requests
      - name: 'start run epic'
        run: python GetFreeEpicGames.py
