name: Python Package using Conda

on:
  schedule:
    - cron: '*/30 * * * *'
  watch:
    types: [started]

jobs:
  epic_game:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Set up Python 3.7'
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: pip install -r ./xmly_speed/requirements.txt
      - name: 'start run xmly_speed'
        env:
          IS_MOBILE_NOTICE: ${{ secrets.XMLY_SPEED_COOKIE }}
          BARK_API: ${{ secrets.BARK_API }}
        run: python ./xmly_speed/xmly_speed.py
